# Dockerfile for the pre- and post-processing of the 3D rolling and pitching plate with PetIBM.

FROM mesnardo/petibm-rollingpitching:PetIBM0.5.1-xenial
MAINTAINER Olivier Mesnard <mesnardo@gwu.edu>

# Install basic requirements
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        autotools-dev build-essential ca-certificates curl git pkg-config vim wget && \
    # VisIt dependencies
    apt-get install -y --no-install-recommends \
        libsm6 libxrender1 libfontconfig1 libxt6 libxext6 libgl1-mesa-dev && \
    # PyDistMesh dependencies
    apt-get install -y --no-install-recommends \
        liblapack-dev && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN VERSION=2.12.3 && \
    TARBALL=visit2_12_3.linux-x86_64-ubuntu14-wmesa.tar.gz && \
    URL=http://portal.nersc.gov/project/visit/releases/${VERSION}/${TARBALL} && \
    wget ${URL} -P /tmp && \
    mkdir -p /opt/visit && \
    tar -xzf /tmp/${TARBALL} -C /opt/visit --strip-components=1 && \
    rm -f /tmp/${TARBALL}

ENV VISIT_DIR=/opt/visit/2.12.3
ENV VISIT_ARCH=linux-x86_64
ENV PATH=/opt/visit/bin:${PATH}

# Install Miniconda3-4.9.2
RUN VERSION=4.9.2 && \
    FILENAME=Miniconda3-py39_${VERSION}-Linux-x86_64.sh && \
    URL=https://repo.anaconda.com/miniconda/${FILENAME} && \
    wget ${URL} -P /tmp && \
    bash /tmp/${FILENAME} -b -p /opt/miniconda3 && \
    rm -f /tmp/${FILENAME}

# Create conda environment for VisIt
RUN . /opt/miniconda3/bin/activate && \
    conda create --name=py27-visit python=2.7 numpy pathlib pyyaml

# Install petibmpy-0.2
RUN VERSION=0.2 && \
    TARBALL=v${VERSION}.tar.gz && \
    URL=https://github.com/mesnardo/petibmpy/archive/refs/tags/${TARBALL} && \
    wget ${URL} -P /tmp && \
    mkdir -p /opt/petibmpy && \
    tar -xzf /tmp/${TARBALL} -C /opt/petibmpy --strip-components=1 && \
    rm -f /tmp/${TARBALL} && \
    . /opt/miniconda3/bin/activate && \
    cd /opt/petibmpy && \
    conda env create --name=py36-rolling --file=environment.yaml && \
    conda activate py36-rolling && \
    python setup.py install && \
    conda deactivate

# Install pydistmesh-1.2
RUN VERSION=1.2 && \
    TARBALL=v${VERSION}.tar.gz && \
    URL=https://github.com/bfroehle/pydistmesh/archive/refs/tags/${TARBALL} && \
    wget ${URL} -P /tmp && \
    mkdir -p /opt/pydistmesh && \
    tar -xzf /tmp/${TARBALL} -C /opt/pydistmesh --strip-components=1 && \
    rm -f /tmp/${TARBALL} && \
    . /opt/miniconda3/bin/activate && \
    cd /opt/pydistmesh && \
    conda activate py36-rolling && \
    python setup.py install && \
    conda deactivate

# Install rodney-0.1
ADD https://api.github.com/repos/mesnardo/petibm-rollingpitching/git/refs/heads/master version.json
RUN URL=https://github.com/mesnardo/petibm-rollingpitching.git && \
    PETIBMAPP_DIR=/tmp/petibm-rollingpitching && \
    git clone --recursive ${URL} ${PETIBMAPP_DIR} && \
    . /opt/miniconda3/bin/activate && \
    cd ${PETIBMAPP_DIR}/src/python && \
    conda activate py36-rolling && \
    pip install --no-deps . && \
    conda deactivate && \
    cp ${PETIBMAPP_DIR}/src/python/visitplot.py /opt/miniconda3/envs/py27-visit/lib/python2.7 && \
    rm -rf ${PETIBMAPP_DIR}

USER petibm-user
RUN echo "source /opt/miniconda3/etc/profile.d/conda.sh" >> ${HOME}/.bashrc && \
    echo "conda activate py36-rolling" >> ${HOME}/.bashrc
WORKDIR /home/petibm-user

EXPOSE 23
CMD ["/usr/sbin/sshd", "-D", "-p", "23"]
